using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace TradeCompanyV2
{
    public partial class ShowInfo : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        
        protected void ButtonOrderAdd_Click(object sender, EventArgs e)
        {
            PanelNewOrder.Visible = true;
        }

        protected void ButtonSaveOrder_Click(object sender, EventArgs e)
        {
            SqlDataSource2.Insert();
            GridView2.DataBind();
            ClearNewOrder();
            HideNewOrderPanel();
        }

        protected void ButtonCancelOrder_Click(object sender, EventArgs e)
        {
            ClearNewOrder();
            HideNewOrderPanel();
        }


        private void HideNewOrderPanel()
        {
            PanelNewOrder.Visible = false;
        }

        private void ClearNewOrder()
        {
            ProductName.Text = string.Empty;
            ProductPrice.Text = string.Empty;
            ProductCount.Text = string.Empty;
        }

        protected void ButtonOrderEdit_Click(object sender, EventArgs e)
        {
            if (GridView2.AutoGenerateEditButton == true)
            {
                GridView2.AutoGenerateEditButton = false;
                ButtonOrderEdit.Text = "Редактировать";
            }
            else
            {
                GridView2.AutoGenerateEditButton = true;
                ButtonOrderEdit.Text = "Закончить редактирование";
            }
        }

        protected void ButtonOrderDelete_Click(object sender, EventArgs e)
        {
            if (GridView2.AutoGenerateDeleteButton == true)
            {
                GridView2.AutoGenerateDeleteButton = false;
                ButtonOrderEdit.Text = "Удалить";
            }
            else
            {
                GridView2.AutoGenerateDeleteButton = true;
                ButtonOrderEdit.Text = "Закончить удаление";
            }
        }

        protected void ButtonCustomerNew_Click(object sender, EventArgs e)
        {
            PanelCustomerAdd.Visible = true;
        }

        protected void ButtonCustomerSave_Click(object sender, EventArgs e)
        {
            SqlDataSource1.Insert();
            GridView1.DataBind();
            ClearNewCustomer();
            HideNewCustomerPanel();
        }

        private void HideNewCustomerPanel()
        {
            PanelCustomerAdd.Visible = false;
        }

        private void ClearNewCustomer()
        {
            CustomerName.Text = string.Empty;
            CustomerSurname.Text = string.Empty;
            CustomerBirthYear.Text = string.Empty;
        }

        protected void ButtonCustomerSaveCancel_Click(object sender, EventArgs e)
        {
            ClearNewCustomer();
            HideNewCustomerPanel();
        }

        protected void ButtonCustomerEdit_Click(object sender, EventArgs e)
        {
            if (GridView1.AutoGenerateEditButton == true)
            {
                GridView1.AutoGenerateEditButton = false;
                ButtonCustomerEdit.Text = "Редактировать";
            }
            else
            {
                GridView1.AutoGenerateEditButton = true;
                ButtonCustomerEdit.Text = "Закончить редактирование";
            }
        }

        protected void ButtonCustomerDelete_Click(object sender, EventArgs e)
        {
            if (GridView1.AutoGenerateDeleteButton == true)
            {
                GridView1.AutoGenerateDeleteButton = false;
                ButtonOrderEdit.Text = "Удалить";
            }
            else
            {
                GridView1.AutoGenerateDeleteButton = true;
                ButtonOrderEdit.Text = "Закончить удаление";
            }
        }
    }
}